version: '3.5'
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.2-latest
    ports:
      - '10051:10051'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /zabbix/zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - /zabbix/zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - /zabbix/zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - /zabbix/zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - /zabbix/zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - /zabbix/zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - /zabbix/zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - snmptraps:/var/lib/zabbix/snmptraps:rw
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    environment:
      - MYSQL_USER_FILE=/run/secrets/MYSQL_USER
      - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
    env_file:
      - /zabbix/env_vars/.env_db_mysql
      - /zabbix/env_vars/.env_srv
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    depends_on:
      - mysql-server
    hostname: zabbix-server
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-server
          - zabbix-server-mysql
          - zabbix-server-alpine-mysql
          - zabbix-server-mysql-alpine
      zbx_net_frontend:
    stop_grace_period: 30s
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
    labels:
      com.zabbix.description: 'Zabbix server with MySQL database support'
      com.zabbix.company: 'Zabbix LLC'
      com.zabbix.component: 'zabbix-server'
      com.zabbix.dbtype: 'mysql'
      com.zabbix.os: 'alpine'

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.2-latest
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /zabbix/zbx_env/etc/ssl/nginx:/etc/ssl/nginx:ro
      - /zabbix/zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    environment:
      - MYSQL_USER_FILE=/run/secrets/MYSQL_USER
      - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD
    env_file:
      - /zabbix/env_vars/.env_db_mysql
      - /zabbix/env_vars/.env_web
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD
    depends_on:
      - mysql-server
      - zabbix-server
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-web-nginx-mysql
          - zabbix-web-nginx-alpine-mysql
          - zabbix-web-nginx-mysql-alpine
      zbx_net_frontend:
    stop_grace_period: 10s
    sysctls:
      - net.core.somaxconn=65535
    labels:
      com.zabbix.description: 'Zabbix frontend on Nginx web-server with MySQL database support'
      com.zabbix.company: 'Zabbix LLC'
      com.zabbix.component: 'zabbix-frontend'
      com.zabbix.webserver: 'nginx'
      com.zabbix.dbtype: 'mysql'
      com.zabbix.os: 'alpine'

  mysql-server:
    image: mariadb:10.5
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --skip-character-set-client-handshake
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - /zabbix/zbx_env/var/lib/mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_USER_FILE=/run/secrets/MYSQL_USER
      - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
    env_file:
      - /zabbix/env_vars/.env_db_mysql
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    stop_grace_period: 1m
    networks:
      zbx_net_backend:
        aliases:
          - mysql-server
          - zabbix-database
          - mysql-databasse

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.2-latest
    ports:
      - '10050:10050'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /zabbix/zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - /zabbix/zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - /zabbix/zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - /zabbix/zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    env_file:
      - /zabbix/env_vars/.env_agent
    hostname: zabbix-agent
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-agent
          - zabbix-agent-passive
          - zabbix-agent-alpine

  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:alpine-6.2-latest
    ports:
      - '10052:10052'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    env_file:
      - /zabbix/env_vars/.env_java
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-java-gateway
          - zabbix-java-gateway-alpine
    stop_grace_period: 5s
    labels:
      com.zabbix.description: 'Zabbix Java Gateway'
      com.zabbix.company: 'Zabbix LLC'
      com.zabbix.component: 'java-gateway'
      com.zabbix.os: 'alpine'

  grafana-server:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /zabbix/zbx_env/etc/ssl/grafana:/etc/ssl/grafana:ro
      - /zabbix/zbx_env/grafana/config/.grafana.ini:/etc/grafana/grafana.ini
      - /zabbix/zbx_env/grafana/plugins:/var/lib/grafana/plugins:rw  
      - grafana-storage:/var/lib/grafana:rw
    env_file:
      - /zabbix/env_vars/.env_grafana
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-grafana
      zbx_net_frontend:

networks:
  zbx_net_frontend:
    driver: overlay
    driver_opts:
      com.docker.network.enable_ipv6: 'false'
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
  zbx_net_backend:
    driver: overlay
    driver_opts:
      com.docker.network.enable_ipv6: 'false'
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24

volumes:
  snmptraps:
  grafana-storage:

secrets:
  MYSQL_USER:
    external: true
  MYSQL_PASSWORD:
    external: true
  MYSQL_ROOT_PASSWORD:
    external: true
